@startuml


[Address]

component address <<Extension>> as "PH Address"

component identification <<Extension>> as "PH Identification"

address -up-> Address : extends >

[core]

database FDA {
[drugs]
}

database "Philippine Standards" {

package "Classification" {
component CED  <<CodeSystem>> as "Education"
component OC  <<CodeSystem>> as "Occupation"
}

component GC <<CodeSystem>> as"Geographic Code" 

GC -up- Barangay
GC -up- City
GC -up- Province
GC -up- Region

}

core .do.> OC
core .do.> CED
core .do.> drugs

address -do-> Barangay
address -do-> City
address -do-> Province
address -do-> Region

database PhilHealth {

component PDD as "Dialysis"

component PHID as "Members"


}

@enduml
