@startuml

'More example available at https://plantuml.com/component-diagram

actor me

interface LAUNCH_UI as "Smart Launch Web UI"

me -do-> LAUNCH_UI : define the link and launch 

interface FORMS_SERVER as "SDC Forms Server"

interface SMART_CDR as "Smart Clinical Data Repository"


[SMART proxy] -up- SMART_CDR
interface CDR as "Clinical Data Repository"


[SMART proxy] -do-> CDR : "localhost:8080"

database "Postgres" as PG
component HAPI <<FHIR R4>>


database samples

[curl]

me -do-> curl : upload some samples

curl -up-> samples

[HAPI] -up- CDR 


curl -do-> HAPI

[Smart Launcher] -up- LAUNCH_UI


interface SMART as "Smart App"


[Smart Launcher] -do-> SMART

[Smart Launcher] -do-> SMART_CDR : localhost:8081

[Smart Forms] -up- SMART

[Smart Forms] .do.> SMART_CDR

[Smart Forms] .do.> FORMS_SERVER

me -do-> [Smart Forms]


component formsRepo <<FHIR R4>>

[formsRepo] -up- FORMS_SERVER

[HAPI] -do-> PG

@enduml
