name: Bug Report
description: Report a bug or issue with the PH Core Implementation Guide
title: "[BUG] "
labels: ["bug"]
body:
  - type: checkboxes
    id: tested-main
    attributes:
      label: Did you test the latest branch Main?
      description: Please confirm you have tested against the latest main branch before reporting.
      options:
        - label: Yes, I have tested on the latest main branch
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: bug-timeline
    attributes:
      label: Bug Timeline
      description: When did you first notice this bug? Has it occurred before?
      placeholder: Describe when this issue started or was discovered...
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages or logs.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the problem.
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error...
    validations:
      required: true

  - type: input
    id: ig-version
    attributes:
      label: Version of IG
      description: What version of the Implementation Guide are you using?
      placeholder: e.g., 0.1.0, main branch, etc.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information & File Uploads
      description: Add any other context, screenshots, or relevant files.
      placeholder: Add any additional information here...
    validations:
      required: false
