name: Feature Request — Delete (FR-D)
description: Request to remove content or functionality from the IG
title: "[FR-D] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Describe what you want to delete
      description: Provide a clear description of what should be removed and why.
      placeholder: Describe what to delete and the rationale...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or references.
      placeholder: Add any additional context here...
    validations:
      required: false
