name: Feature Request — Update (FR-U)
description: Request to modify or update existing IG content
title: "[FR-U] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the update you want
      description: Provide a clear description of what should be modified.
      placeholder: Describe what to update and how...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Add any additional context here...
    validations:
      required: false
