name: Feature Request — Add (FR-A)
description: Request to add new functionality or content to the IG
title: "[FR-A] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you want to add
      description: Provide a clear description of what you want to add.
      placeholder: Describe the new feature/content here...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Add any additional context here...
    validations:
      required: false
