name: Feature Request — Other (FR-O)
description: Other types of feature requests or changes
title: "[FR-O] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature or change you want
      description: Provide a clear description of what you need.
      placeholder: Describe the feature/change here...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Add any additional context here...
    validations:
      required: false
