name: Task
description: Create a task for maintenance, documentation, or other non-feature work
title: "[T] "
labels: ["task"]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Provide a clear description of the task to be completed.
      placeholder: Describe the task here...
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this task needed? What problem does it solve?
      placeholder: Explain why this task is important...
    validations:
      required: false

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What should be the result when this task is completed?
      placeholder: Describe the expected outcome...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, resources, or references.
      placeholder: Add any additional context here...
    validations:
      required: false
